@startmindmap
' top to bottom direction

' Aussschluss TNM / UICC
'   - "no_stadium": (C80, C76, C70-C72, C81-96, C44) OR HIST >= 8800
' - "in_situ": D00-D09 (ohne Haut: D04)
' - "system": C81-C96, D45-D47
' - "solid": C00-C80, ohne C44 (C77-C79 sollten nicht drin sein)
' - "BET": 5-870, 5-877

+ data quality

++ Bericht
+++ Einführung
++++_ Gesetz
++++_ Umsetzung Konkretisierung
++++_ Datensatz vs oBDS epi+klin
++++_ Zusammenarbeit mit kkr
+++ Datenqualität
++++ Begriffe
+++++_ Indikatoren
+++++_ eingeschlossene icd10
+++++_ Limitationen
++++ Vollzähligkeitsschätzung
++++ Aktualität
++++ Vollständigkeit **Personenangaben**
++++ Vollständigkeit **Tumorangaben** Anteile
+++++[#Gray] Mehrfachtumore (epi vs klin)
+++++ Diagnosesicherung
+++++ DCO
+++++ missing TNM / UICC
++++++_ UICC nur epi

+++++ Histo unspezifisch
+++++ Topo unspezifisch (PSU)
+++++ missing Grading
+++++ missing Organmodul
++++++_ Gleason
++++++_ Hormonrezeptor
+++++ missing OPS wenn OP vorhanden

++++ Vollständigkeit **Therapie**
+++++ Vorbemerkung
++++++_ nicht durchgeführt vs nicht erhalten
++++++_ Einschluss
++++++_ Ausschluss: Pat verstorben in 3/6m
+++++ Beschreibung systematischer Datenlücken
+++++ Anteil Fälle ohne Therapie D vs kkr
++++++_ solide
++++++_ in-situ
++++++_ System
+++++ Anteil Fälle ohne Therapie wenn Therapie erwartbar ist\n(jeweils kein M1 und nicht verstorben < 6m)
++++++_ in situ
++++++_ system
++++++_ solid
+++++ Anteil Fälle ohne OP wenn OP erwartbar ist
++++++_ Brust
++++++_ Darm
++++++_ Hoden
++++++_ Melanom
+++++ Anteil Fälle ohne ST wenn ST erwartbar ist
++++++_ Brust (ops=BET, no M1)
+++++ Anteil Fälle ohne SYST wenn SYST erwartbar ist
+++++_ (C91.0, C92.0...) Akute Leuk. + Lyphome
+++++ Anteil Fälle ohne R-Status nach OP wenn hohe Relevanz des R-Status
++++++_ Mamma
+++++ Verlaufsangaben
++++++ Vorbemerkung
+++++++_ nur deskriptiv
+++++++_ Vollständigkeit nicht beurteilbar
+++++++_ noch kein Goldstandard
++++++ Systematische Datenlücken
++++++ Anteil Lokalrezidive (erstmal breite Definition)
+++++++_ Brust, Harnblase, Prostata, Darm
+++++++_ bis Ende 2023 nach R0-Status\nDiagnose 2020-2021
++++++[#Gray] Anteil LK und FM
+++++++_ bis Ende 2023\nDiagnose 2020-2021

++++ Qualität der Sterbeinformationen und Vitalstatus
+++++ Untererfassung Sterbeinformationen
++++++_ Oberbayern
++++++_ ST
++++++_ TH
+++++ Zensierung der Fälle aus NBL bis 2019
++++++_ Daten stammen aus GKR\nVitalstatus noch niocht aktualisiert
+++++ mögliche Überschätzung der Überlebensraten
++++++_ Pankreas (außer NET)
++++++_ Lunge UICC III/IV
++++++_ Glioblastom
++++++_ HCC (Leber)

+++ Antragsbearbeitung und Datenbereitstellung
++++ Beschreibung der Verfahren
++++ Statistiken zu Datenanträgen
+++++ Nach Jahr der Antragsstellung
+++++ Nach Themen
+++++ Nach Art des AS
++++++_ Universität
++++++_ sonstige öffentliche Einrichtungen
++++++_ private Einrichtungen
++++ Veröffentlichungen aus bewilligten Datennutzungsanträgen
+++ Diskussion, Einordnung, Ausblick
++++ Einordnung im internationalen / europäischen Kontext
++++ Zusammenfassung noch bestehender Limitationen und Diskussion möglicher Gründe
+++++_ Initiativen KKR + ZfKD
++++ Ausblick
+++++_ Möglichkeit der Verlinkung mit Abrechnungsdaten nach GDNG

'-------------------------------------

++ Inhaltlich
+++[#IndianRed] Fallzahlen
++++ aktuelles Lieferjahr
++++ Lieferjahre im Vergleich
+++ missings
++++ fehlende nodes
+++++_ relative Anteile z.B. OP / Tumor
++++ fehlende Felder
+++++_ Ampelvergleiche
+++ Vollzähligkeit
++++_ epi vs klin: für Abschätzung der Vollzähligkeit
+++ Verteilung von Variablen
++++[#IndianRed] Datumsangaben
+++++_ Abstand 0 Tage gruppiert
+++++_ Vergleich Gesamt vs einzelne Entitäten
++++[#IndianRed] Numerische Werte
+++++_ Boxplots
+++++_ Werteklassen
++++ Kodierte Werte
+++++_ Relative Anteile
+++++_ evtl Besonderheiten
+++ Organspez. Auswertungen
++++ Entitäten
+++++ C07
+++++ C18-C20
+++++ C25
+++++ C50 (therapien, leitlinien)
+++++ C61
++++ relative Verteilungen
++++ klinische Fragestellungen
+++ Themenspez. Auswertungen
++++_ Rezidive
++++_ Datumsabstände
++++_ FM
++++ Verlaufsereignisse
++++ Referenzgruppen als Teilmenge -> erwartetete op
+++[#IndianRed] Unstrukturierte Angaben
++++ Weitere Klassifikationen
++++ Freitexte (Substanzen, Protokolle)
+++ Plausibilität
++++_ Metriken (ABC)

++[#IndianRed] Technisch
+++ missings
+++ ungültige Werte
++++_ Auflistungen
+++ duplikate
++++_ echt
++++_ unecht
++++_ verdacht

++ Umsetzung
+++ Formate
++++ Datenbericht (pdf)
++++ Öffentliches DQ Repository\n(geplant)
+++++_ für Register
+++++_ für Antragsteller
+++++_ für Fachöffentlichkeit
+++ Prozesse
++++[#IndianRed] Standardisierung
+++++ Referenzlisten (in repo)
+++++ Zusatzvariablen (z_)
++++++ Bereinigungen
++++++ komplexe Berechnungen
+++++ Rückmeldung in Datenbereitstellung integriert
++++ Offene Weiterentwicklung
+++++_ Nutzung moderner Plattformen
+++++_ Daten, Code und Dokumentation an einem Ort

@endmindmap