@startwbs tnm

' <style>
' wbsDiagram {
'     LineColor #4682B4
'     Node {
'         BackgroundColor White
'         RoundCorner 0
'     }
'     .dashed {
'         LineStyle 4
'         LineColor Blue
'     }
' }
' </style>

* Tumore\n(TNM-relevante Diagnose)
** Histologisch gesichert (Primärtumor) (h)
*** Grading liegt vor* (g)
*** pT liegt vor (a)
**** pN liegt vor (f)
**** Relevante OP (b)
***** Gültiger R-Status
******_ ja (d)
******_ nein
**** Keine relevante OP
*** pT liegt nicht vor
**** Relevante OP (c)
***** Gültiger R-Status
******_ ja (e)
******_ nein
**** Keine relevante OP
** Andere Diagnosesicherung

@endwbs