name: Deploy Dev Docs to GH Pages
on:
  push:
    branches:
      - dev  # ONLY triggers when you push to the dev branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Deploy to GH Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/html # Change this if you use docs/html
          branch: gh-pages      # The website branch
          clean: true           # Deletes old files on the gh-pages branch